[package]
name = "slint-interface"
version = "0.1.0"
edition = "2024"

[dependencies]
backends = {path = "../backends"}

slint = { version = "1.11", features = [
    "renderer-femtovg",
    "backend-winit",
] }
log = "0.4.26"

[build-dependencies]
slint-build = "=1.11.0"
