export component ErrorWindow inherits Window {
    in property <string> text <=> t.text;
    in property <string> hint <=> title.text;
    height: 100px;
    width: 500px;
    VerticalLayout {
        title := Text {
            font-size: 24px;
            horizontal-alignment: TextHorizontalAlignment.left;
        }

        t := Text {
            font-size: 20px;
            horizontal-alignment: TextHorizontalAlignment.center;
        }
    }
}
