import { TabWidget, ScrollView, LineEdit, Button } from "std-widgets.slint";

component ApiKeyStripe inherits HorizontalLayout {
    in property <string> api-name <=> api-name-text.text;
    in property <string> api-key <=> api-key-lineedit.text;

    api-name-text := Text {
        width: 100px;
        font-size: 16px;
    }

    api-key-lineedit := LineEdit {
        font-size: 16px;
    }
}

export component SettingWindow inherits Window {
    preferred-width: 400px;
    preferred-height: 250px;

    in property <string> deepseek-api-key <=> deepseek-stripe.api-key;
    in property <string> qwen-api-key <=> qwen-stripe.api-key;

    VerticalLayout {
        TabWidget {
            Tab {

                title: "API Keys from AI providers";

                VerticalLayout {
                    alignment: LayoutAlignment.start;
                    deepseek-stripe := ApiKeyStripe {
                        api-name: "DeepSeek";
                        api-key: "";
                    }

                    qwen-stripe := ApiKeyStripe {
                        api-name: "Qwen";
                        api-key: "";
                    }
                }
            }
        }

        @children
    }
}
