import { LineEdit, HorizontalBox, Button, VerticalBox, Palette, Switch, TabWidget, TextEdit } from "std-widgets.slint";
import { AboutSlintWindow } from "about.slint";

/*
The structure is as followed:

+--------------------------------------------+
|               MainWindow                   |
| +----------------------------------------+ |
| |            base-area                   | |
| | +------------------------------------+ | |
| | |    header-area (HorizontalBox)     | | |
| | +------------------------------------+ | |
| | |       main-area (HorizontalBox)    | | |
| | | +--------------------------------+ | | |
| | | |      TabWidget Titles          | | | |
| | | | +----------------------------+ | | | |
| | | | |         Tabs               | | | | |
| | | | +----------------------------+ | | | |
| | | +--------------------------------+ | | |
| | +------------------------------------+ | |
| +----------------------------------------+ |
*/

export global Logic {
    // Implementation of this callback is seen in the business logic (Rust script).
    pure callback translate-word(string) -> string;
    pure callback show-about-slint();
    pure callback translate-sentence(string) -> string;
}

export component AboutSlintWindow inherits AboutSlintWindow { }

export component MainWindow inherits Window {

    min-height: 500px;
    preferred-height: self.min-height;

    min-width: 800px;
    preferred-width: self.min-width;

    base-area := VerticalBox {

        header-area := HorizontalBox {
            alignment: LayoutAlignment.space-between;

            HorizontalLayout {
                Text {
                    text: "Neat Translator";
                    font-size: 20px;

                    horizontal-alignment: TextHorizontalAlignment.center;
                    wrap: TextWrap.word-wrap;
                }
            }

            HorizontalLayout {
            // Switch Light/Dark Mode
            Switch {
                    horizontal-stretch: 0;
                    text: @tr("Dark Mode");
                    checked: Palette.color-scheme == ColorScheme.dark;
                    toggled => {
                        Palette.color-scheme = !(Palette.color-scheme == ColorScheme.dark) ? ColorScheme.dark : ColorScheme.light;
                    }
                }

            // About Slint
            Button {
                    text: @tr("About Slint");
                    clicked => {
                    // Show about dialog
                    // about-slint.show();
                    Logic.show-about-slint()
                    }
                }
            }
        }

        main-area := HorizontalBox {
            property <length> left-fix-width: 100px;

            alignment: LayoutAlignment.stretch;

            TabWidget {

                Tab {
                    title: "Word";
                    VerticalLayout {
                        HorizontalBox {
                            max-height: search-line-edit.min-height;
                            search-line-edit := LineEdit {
                                height: 50px;
                                font-size: 24px;
                                accepted => {
                                    t-word.text = Logic.translate-word(search-line-edit.text);
                                    search-line-edit.select-all();
                                    // Implement translation logic here
                                }
                            }

                            Button {
                                text: "Translate";
                                clicked => {
                                    t-word.text = Logic.translate-word(search-line-edit.text)
                                    // Implement translation logic here
                                }
                            }
                        }

                        t-word := Text {
                            text: "";
                            font-size: 16px;
                            wrap: TextWrap.word-wrap;
                        }
                    }
                }

                Tab {
                    title: "Sentences";

                    private property <int> seconds: 1;
                    private property <string> old-string;
                    private property <string> new-string;

                    timer := Timer {
                        interval: 1s;
                        running: false;
                        triggered() => {
                            debug("Timer of sentense is activated!");
                            new-string = original-text.text;
                            if (old-string == new-string) {
                                translated-text.text = Logic.translate-sentence(new-string);
                                self.running = false;
                            }
                        }
                    }

                    HorizontalBox {
                        alignment: LayoutAlignment.stretch;
                        original-text := TextEdit {
                            width: 50%;
                            font-size: 16px;
                            wrap: TextWrap.word-wrap;

                            edited(text) => {
                                debug("Text is edited!");
                                old-string = self.text; // TODO: Buggy! The value of old-string will change! It is only a pointer!
                                timer.running = true;
                            }
                        }

                        translated-text := Text {
                            width: 50%;
                            font-size: 16px;
                            wrap: TextWrap.word-wrap;
                        }
                    }
                }
            }
        }
    }
}
